# Generated by Django 3.2.4 on 2021-06-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecto2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
