# Generated by Django 3.2.4 on 2021-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto2', '0003_contacto_encomendar_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Encomendar',
        ),
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
