# Generated by Django 3.2.4 on 2021-06-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto2', '0005_auto_20210629_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomendar',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
